# Generated by Django 5.1.7 on 2025-03-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='nome',
            new_name='nome_loja',
        ),
    ]
